In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
movies = pd.read_csv('/Users/dhruvitjalodhara/programming/ML Practice/Movie Recommendation System/movie dataset/processed/filtered_movies.csv')
ratings = pd.read_csv('/Users/dhruvitjalodhara/programming/ML Practice/Movie Recommendation System/movie dataset/processed/filtered_ratings.csv')

In [3]:
movies.shape , ratings.shape

((16116, 5), (29657653, 3))

In [4]:
ratings

,userId,movieId,rating
0,1,1,4.0
1,1,110,4.0
2,1,158,4.0
3,1,260,4.5
4,1,356,5.0
...,...,...,...
29657648,330975,8340,2.0
29657649,330975,8493,2.5
29657650,330975,8622,4.0
29657651,330975,8665,3.0


In [5]:
ratings = ratings.pivot(index='movieId' , columns='userId' , values='rating')

In [6]:
ratings = ratings.fillna(0)

In [7]:
ratings

userId,1,2,7,9,10,12,14,17,21,22,...,330951,330957,330960,330961,330967,330970,330971,330972,330974,330975
movieId,,,,,,,,,,,,,,,,,,,,,
1,4.0,5.0,4.0,0.0,3.0,5.0,2.5,0.0,3.0,0.0,...,5.0,0.0,0.0,4.0,0.0,0.0,0.0,3.0,0.0,2.5
2,0.0,3.0,0.0,4.0,0.0,0.0,2.5,0.0,3.0,0.0,...,4.0,0.0,0.0,2.5,0.0,0.0,0.0,0.0,3.0,2.0
3,0.0,0.0,3.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,1.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
287377,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
287633,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
288167,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0


In [8]:
# Compress into a CSR Matrix : A Compressed Sparse Row (CSR) matrix completely ignores the zeros in memory and only tracks the exact row/column coordinates of the actual numeric ratings.
from scipy.sparse import csr_matrix

ratings_csr = csr_matrix(ratings.values)

In [9]:
print("--- MATRIX ENGINEERING SUCCESSFUL ---")
print(f"Pivot DataFrame Shape : {ratings.shape}")
print(f"Compressed Sparse CSR Shape: {ratings_csr.shape}")


--- MATRIX ENGINEERING SUCCESSFUL ---
Pivot DataFrame Shape : (16116, 130306)
Compressed Sparse CSR Shape: (16116, 130306)


In [10]:
## Training model by KNN
from sklearn.neighbors import NearestNeighbors

model_knn = NearestNeighbors(metric='cosine' , algorithm='brute' , n_neighbors=20)
model_knn.fit(ratings_csr)

,"n_neighbors n_neighbors: int, default=5Number of neighbors to use by default for :meth:`kneighbors` queries.",20
,"algorithm algorithm: {'auto', 'ball_tree', 'kd_tree', 'brute'}, default='auto'Algorithm used to compute the nearest neighbors:- 'ball_tree' will use :class:`BallTree`- 'kd_tree' will use :class:`KDTree`- 'brute' will use a brute-force search.- 'auto' will attempt to decide the most appropriate algorithm based on the values passed to :meth:`fit` method.Note: fitting on sparse input will override the setting ofthis parameter, using brute force.",'brute'
,"metric metric: str or callable, default='minkowski'Metric to use for distance computation. Default is ""minkowski"", whichresults in the standard Euclidean distance when p = 2. See thedocumentation of `scipy.spatial.distance<https://docs.scipy.org/doc/scipy/reference/spatial.distance.html>`_ andthe metrics listed in:class:`~sklearn.metrics.pairwise.distance_metrics` for valid metricvalues.If metric is ""precomputed"", X is assumed to be a distance matrix andmust be square during fit. X may be a :term:`sparse graph`, in whichcase only ""nonzero"" elements may be considered neighbors.If metric is a callable function, it takes two arrays representing 1Dvectors as inputs and must return one value indicating the distancebetween those vectors. This works for Scipy's metrics, but is lessefficient than passing the metric name as a string.",'cosine'
,"radius radius: float, default=1.0Range of parameter space to use by default for :meth:`radius_neighbors`queries.",1.0
,"leaf_size leaf_size: int, default=30Leaf size passed to BallTree or KDTree. This can affect thespeed of the construction and query, as well as the memoryrequired to store the tree. The optimal value depends on thenature of the problem.",30
,"p p: float (positive), default=2Parameter for the Minkowski metric fromsklearn.metrics.pairwise.pairwise_distances. When p = 1, this isequivalent to using manhattan_distance (l1), and euclidean_distance(l2) for p = 2. For arbitrary p, minkowski_distance (l_p) is used.",2
,"metric_params metric_params: dict, default=NoneAdditional keyword arguments for the metric function.",None
,"n_jobs n_jobs: int, default=NoneThe number of parallel jobs to run for neighbors search.``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.``-1`` means using all processors. See :term:`Glossary <n_jobs>`for more details.",None
Name,Type,Value
effective_metric_ effective_metric_: strMetric used to compute distances to neighbors.,str,'cosine'
effective_metric_params_ effective_metric_params_: dictParameters for the metric used to compute distances to neighbors.,dict,{}


In [11]:
# 1. Create a helper series matching movie titles to their matrix row numbers
# We reset the index of ratings to get numerical positions (0, 1, 2...)
matrix_movie_ids = pd.DataFrame({'movieId': ratings.index})

# 2. Merge with the movies dataframe to get the matching titles for those rows
# This ensures perfect row alignment and records the matrix index position
mapping_df = pd.merge(matrix_movie_ids, movies, on='movieId').reset_index()

# 3. Create the final Series: index is 'title', values are the matrix row positions ('index')
movie_to_idx = pd.Series(mapping_df['index'].values, index=mapping_df['title'])

print("--- MAPPING REFERENCE CREATED ---")
print(f"Total mapped movies: {len(movie_to_idx)}")

movie_to_idx

--- MAPPING REFERENCE CREATED ---
Total mapped movies: 16116


title
Toy Story (1995)                                            0
Jumanji (1995)                                              1
Grumpier Old Men (1995)                                     2
Waiting to Exhale (1995)                                    3
Father of the Bride Part II (1995)                          4
                                                        ...  
Fast X (2023)                                           16111
Asteroid City (2023)                                    16112
Extraction 2 (2023)                                     16113
Mission: Impossible - Dead Reckoning Part One (2023)    16114
Nimona (2023)                                           16115
Length: 16116, dtype: int64

In [14]:
search_title = "Death Note: Desu nôto (2006–2007)"

# Step 1: Use your mapping reference to look up that movie's exact row index
try:
	movie_matrix_idx = movie_to_idx[search_title]
	print(f"✅ Found '{search_title}' at Matrix Row Index: {movie_matrix_idx}\n")
except KeyError:
	print(f"❌ '{search_title}' not found. Please double-check the exact spelling/year.")
	movie_matrix_idx = None

if movie_matrix_idx is not None:

	# Step 2: Extract that specific row's data vector from your pivoted ratings dataframe
	movie_vector = ratings.iloc[movie_matrix_idx].values

	# Step 3: Pass vector into kneighbors(), reshaping it into a 2D array (.reshape(1, -1))
	# We request 6 neighbors to get the top 5 recommendations (since index 0 is the movie itself)
	distances, indices = model_knn.kneighbors(
	movie_vector.reshape(1, -1),
	n_neighbors=6
	)

	# Step 4: Flatten the returned arrays to make them easy to loop through
	flat_distances = distances.flatten()
	flat_indices = indices.flatten()

	idx_to_movie = {v: k for k, v in movie_to_idx.items()}

	# Step 5: Loop through neighbor indices, look up actual titles, and print results
	print(f"Recommendations for '{search_title}':")
	print("-" * 50)

	# Start loop from 1 to skip the searched movie itself
	for i in range(1, len(flat_indices)):
		neighbor_row_idx = flat_indices[i]
		neighbor_distance = flat_distances[i]

		# Reverse lookup the title from your movie_to_idx series
		#recommended_title = movie_to_idx[movie_to_idx == neighbor_row_idx].index[0]

		recommended_title = idx_to_movie[neighbor_row_idx]

		# Convert distance to a similarity score (1 - distance)
		similarity_score = 1 - neighbor_distance
		print(f"{i}. {recommended_title} (Similarity: {similarity_score:.2%})") 


✅ Found 'Death Note: Desu nôto (2006–2007)' at Matrix Row Index: 14280

Recommendations for 'Death Note: Desu nôto (2006–2007)':
--------------------------------------------------
1. Attack On Titan (2013) (Similarity: 24.59%)
2. Your Name. (2016) (Similarity: 18.58%)
3. Cosmos: A Spacetime Odissey (Similarity: 17.69%)
4. Death Note Rewrite: Genshisuru Kami (2007) (Similarity: 15.31%)
5. Death Note: R2 - L o Tsugu Mono (2008) (Similarity: 14.70%)


In [15]:
## Truncated SVD
from sklearn.decomposition import TruncatedSVD

svd = TruncatedSVD(n_components=50 , random_state=42)
movie_features_svd = svd.fit_transform(ratings_csr)
movie_features_svd

array([[ 6.69728955e+02,  6.96522408e+01, -1.59788279e+02, ...,
        -5.02862530e+01,  1.06573740e+01,  3.04765196e+01],
       [ 2.99412523e+02,  4.46247048e+01, -1.77263682e+02, ...,
        -3.04688462e+01, -2.51396671e+01,  1.32883382e+01],
       [ 9.10340217e+01,  7.75211031e+01, -6.65771807e+01, ...,
        -1.26159403e+01, -9.30641941e+00, -5.59128577e-01],
       ...,
       [ 2.07811455e+00, -1.62300287e+00, -2.24366435e-01, ...,
        -7.59002363e-01, -1.98172754e-01,  4.35546659e-01],
       [ 2.31309354e+00, -1.24165563e+00,  8.69438773e-01, ...,
         7.95553840e-02, -5.38520273e-01,  5.29163983e-02],
       [ 1.19173355e+00, -8.89823512e-01,  1.94343248e-01, ...,
        -2.34543534e-01, -2.54806470e-01,  1.84069545e-01]],
      shape=(16116, 50))

In [16]:
from sklearn.metrics.pairwise import cosine_similarity

svd_sim_matrix = cosine_similarity(movie_features_svd)
svd_sim_matrix


array([[1.        , 0.71689087, 0.51964752, ..., 0.16043375, 0.20311058,
        0.19882178],
       [0.71689087, 1.        , 0.62910967, ..., 0.22980357, 0.22233029,
        0.26443465],
       [0.51964752, 0.62910967, 1.        , ..., 0.10995327, 0.10894178,
        0.07586454],
       ...,
       [0.16043375, 0.22980357, 0.10995327, ..., 1.        , 0.86494284,
        0.71204711],
       [0.20311058, 0.22233029, 0.10894178, ..., 0.86494284, 1.        ,
        0.80917002],
       [0.19882178, 0.26443465, 0.07586454, ..., 0.71204711, 0.80917002,
        1.        ]], shape=(16116, 16116))

In [17]:
# Step 0: Look up the row index for your target movie using the mapping reference
target_movie = "Sultan (2016)"
movie_idx = movie_to_idx[target_movie]

# Step 1: Extract that movie's entire similarity score row from svd_sim_matrix
similarity_row = svd_sim_matrix[movie_idx]

# Step 2: Sort the scores from highest to lowest using np.argsort and reversing it
sorted_indices = np.argsort(similarity_row)[::-1]

# Step 3: Grab the top 6 indices (slicing from index 1 to 6 to skip the target movie itself)
top_6_neighbors = sorted_indices[1:6]

# Step 4: Loop through neighbor indices, reverse-lookup titles, and print them out
print(f"SVD Recommendations for '{target_movie}':")
print("-" * 60)

# Create a fast reverse lookup dictionary from your existing mapping Series
idx_to_movie_dict = {v: k for k, v in movie_to_idx.items()}

for rank, neighbor_idx in enumerate(top_6_neighbors, 1):

	# Reverse lookup the title from your movie_to_idx series
	#recommended_title = movie_to_idx[movie_to_idx == neighbor_idx].index[0]

	recommended_title = idx_to_movie_dict[neighbor_idx]
	
	# Extract the similarity score
	similarity_score = similarity_row[neighbor_idx]
	print(f"{rank}. {recommended_title} (SVD Match: {similarity_score:.2%})") 


SVD Recommendations for 'Sultan (2016)':
------------------------------------------------------------
1. Lage Raho Munna Bhai (2006) (SVD Match: 95.07%)
2. Hera Pheri (2000) (SVD Match: 94.72%)
3. OMG Oh My God! (2012) (SVD Match: 94.68%)
4. Bajrangi Bhaijaan (2015) (SVD Match: 94.57%)
5. Ghajini (2008) (SVD Match: 94.01%)


In [18]:
## Non-Negative Matrix Factorization (NMF)
from sklearn.decomposition import NMF

nmf = NMF(n_components=50, init='random', random_state=42)
movie_features_nmf = nmf.fit_transform(ratings_csr)
movie_features_nmf

array([[0.        , 8.30150343, 5.45604257, ..., 0.71803737, 3.32412619,
        0.17449929],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]], shape=(16116, 50))

In [19]:
from sklearn.metrics.pairwise import cosine_similarity

nmf_sim_matrix = cosine_similarity(movie_features_nmf)
nmf_sim_matrix

array([[1.        , 0.22606951, 0.09440527, ..., 0.        , 0.        ,
        0.04895809],
       [0.22606951, 1.        , 0.44519936, ..., 0.0591358 , 0.05297686,
        0.11532168],
       [0.09440527, 0.44519936, 1.        , ..., 0.00459187, 0.01550878,
        0.00119066],
       ...,
       [0.        , 0.0591358 , 0.00459187, ..., 1.        , 0.90805278,
        0.53333043],
       [0.        , 0.05297686, 0.01550878, ..., 0.90805278, 1.        ,
        0.59425725],
       [0.04895809, 0.11532168, 0.00119066, ..., 0.53333043, 0.59425725,
        1.        ]], shape=(16116, 16116))

In [20]:
# Step 0: Look up the row index for your target movie using the mapping reference
target_movie = "Avengers: Infinity War - Part II (2019)"

try:
    movie_idx = movie_to_idx[target_movie]
    print(f"✅ Found '{target_movie}' at Matrix Row Index: {movie_idx}\n")
    
    # Step 1: Extract that movie's entire similarity score row from nmf_sim_matrix
    similarity_row = nmf_sim_matrix[movie_idx]

    # Step 2: Sort the scores from highest to lowest using np.argsort and reversing it
    sorted_indices = np.argsort(similarity_row)[::-1]

    # Step 3: Grab the top 6 indices (slicing from index 1 to 6 to skip the target movie itself)
    top_6_neighbors = sorted_indices[1:6]

    # Step 4: Loop through neighbor indices, reverse-lookup titles, and print them out
    print(f"NMF Recommendations for '{target_movie}':")
    print("-" * 60)

    # Create your optimized reverse lookup dictionary
    idx_to_movie_dict = {v: k for k, v in movie_to_idx.items()}

    for rank, neighbor_idx in enumerate(top_6_neighbors, 1):
        # Look up the title instantly via your dictionary map
        recommended_title = idx_to_movie_dict[neighbor_idx]
        
        # Extract the similarity score
        similarity_score = similarity_row[neighbor_idx]
        
        print(f"{rank}. {recommended_title} (NMF Match: {similarity_score:.2%})")

except KeyError:
    print(f"❌ '{target_movie}' not found in your filtered dataset.")
    print("This usually means the movie didn't meet your minimum rating cut-off threshold.") 


✅ Found 'Avengers: Infinity War - Part II (2019)' at Matrix Row Index: 12751

NMF Recommendations for 'Avengers: Infinity War - Part II (2019)':
------------------------------------------------------------
1. Spider-Man: Far from Home (2019) (NMF Match: 99.97%)
2. Black Panther (2017) (NMF Match: 99.96%)
3. Thor: Ragnarok (2017) (NMF Match: 99.92%)
4. Avengers: Infinity War - Part I (2018) (NMF Match: 99.90%)
5. Untitled Spider-Man Reboot (2017) (NMF Match: 99.80%)


In [21]:
## K-Means Clusturing
from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=30, random_state=42, n_init='auto')
cluster_labels = kmeans.fit_predict(movie_features_svd)
cluster_labels

array([18, 16,  5, ...,  0,  0,  0], shape=(16116,), dtype=int32)

In [22]:
# Assign directly to mapping_df for perfect index alignment
mapping_df['cluster'] = cluster_labels

mapping_df

,index,movieId,title,genres,tags,metadata_soup,cluster
0,0,1,Toy Story (1995),Adventure Animation Children Comedy Fantasy,animation friendship toys animation Disney Pix...,Adventure Animation Children Comedy Fantasy an...,18
1,1,2,Jumanji (1995),Adventure Children Fantasy,animals based_on_a_book fantasy magic_board_ga...,Adventure Children Fantasy animals based_on_a_...,16
2,2,3,Grumpier Old Men (1995),Comedy Romance,sequel moldy old old_age old_men wedding old_p...,Comedy Romance sequel moldy old old_age old_me...,5
3,3,4,Waiting to Exhale (1995),Comedy Drama Romance,characters chick_flick girl_movie characters c...,Comedy Drama Romance characters chick_flick gi...,2
4,4,5,Father of the Bride Part II (1995),Comedy,family pregnancy wedding 4th_wall aging baby d...,Comedy family pregnancy wedding 4th_wall aging...,5
...,...,...,...,...,...,...,...
16111,16111,287377,Fast X (2023),Action Crime,action bomb car_chase duringcreditsstinger esc...,Action Crime action bomb car_chase duringcredi...,0
16112,16112,287633,Asteroid City (2023),Comedy Drama Romance Sci-Fi,boring 1950s 1955 astronomy children comedy-dr...,Comedy Drama Romance Sci-Fi boring 1950s 1955 ...,0
16113,16113,288167,Extraction 2 (2023),Action Thriller,action betrayal brothers child_in_danger child...,Action Thriller action betrayal brothers child...,0
16114,16114,288265,Mission: Impossible - Dead Reckoning Part One ...,Action Adventure Thriller,action action_packed Christopher_McQuarrie Mis...,Action Adventure Thriller action action_packed...,0


In [23]:
# Step 0: Direct lookup using your exact mapping dictionary/Series keys
search_title = "Kung Fu Panda (2008)"

if search_title in movie_to_idx.index:
	# Get the row index first
	matrix_row_idx = movie_to_idx[search_title]
	# Extract the cluster number directly from that row in mapping_df
	assigned_cluster = mapping_df.loc[matrix_row_idx, 'cluster']
	print(f"🎬 Movie: {search_title} ➡️ Cluster: {assigned_cluster}\n")
	# Step 1: Filter the dataframe to isolate this cluster group
	cluster_group = mapping_df[mapping_df['cluster'] == assigned_cluster]
	# Step 2: Grab and print 5 random movie titles from the same cluster
	print(f"--- 10 Random Neighbors from Cluster {assigned_cluster} ---")
	print(cluster_group['title'].sample(5).to_string(index=False))

else:
	print(f"❌ '{search_title}' not found. Let's look for a partial match:")
	# Fallback to show partial matches if the year or text is slightly off
	matches = mapping_df[mapping_df['title'].str.contains("Avengers", case=False, na=False)]['title'].head()
	print(matches.to_string(index=False)) 


🎬 Movie: Kung Fu Panda (2008) ➡️ Cluster: 27

--- 10 Random Neighbors from Cluster 27 ---
      Zootopia (2016)
       Tangled (2010)
Jurassic World (2015)
Now You See Me (2013)
 Black Panther (2017)


In [24]:
def calculate_batch_mse(W, H, original_csr, batch_size=1000):
	"""
	Calculates Mean Squared Error in small, memory-safe chunks.
	W: Movie features matrix (e.g., movie_features_svd)
	H: Components matrix (e.g., svd.components_)
	original_csr: Your compressed sparse matrix (ratings_csr)
	"""

	total_squared_error = 0.0
	num_movies = original_csr.shape[0]
	total_elements = original_csr.shape[0] * original_csr.shape[1]

	# Process the matrix in small chunks of rows
	for start_idx in range(0, num_movies, batch_size):
		end_idx = min(start_idx + batch_size, num_movies)

		# 1. Get the dense chunk of original ratings directly from the sparse matrix
		actual_chunk = original_csr[start_idx:end_idx].toarray()

		# 2. Reconstruct ONLY this small chunk of rows
		predicted_chunk = np.dot(W[start_idx:end_idx], H)

		# 3. Sum up the squared differences for this chunk
		total_squared_error += np.sum((actual_chunk - predicted_chunk) ** 2)

	# Final step: Divide the grand total by the total number of cells
	return total_squared_error / total_elements

# --- RUN EXECUTION MEMORY-SAFELY ---
print("Calculating TruncatedSVD Error...")
svd_mse = calculate_batch_mse(movie_features_svd, svd.components_, ratings_csr)

print("Calculating NMF Error...")
nmf_mse = calculate_batch_mse(movie_features_nmf, nmf.components_, ratings_csr)

print("\n--- RECONSTRUCTION ERROR CALCULATED ---")
print(f"TruncatedSVD Reconstruction MSE: {svd_mse:.6f}")
print(f"NMF Reconstruction MSE: {nmf_mse:.6f}")


Calculating TruncatedSVD Error...
Calculating NMF Error...

--- RECONSTRUCTION ERROR CALCULATED ---
TruncatedSVD Reconstruction MSE: 0.108398
NMF Reconstruction MSE: 0.113584


In [25]:
# Select a random sample of 200 movie indices to test our models across
np.random.seed(42)
total_unique_movies = ratings.shape[0]
sample_indices = np.random.choice(total_unique_movies, size=200, replace=False)

# Sets to store unique recommended movie row indices
knn_recommended_set = set()
svd_recommended_set = set()
nmf_recommended_set = set()

print("Calculating coverage for 200 sample movies...")

for idx in sample_indices:
	# --- KNN Coverage ---
	# Using ratings_csr[idx] directly avoids unpack crashes and preserves memory
	_, indices_knn = model_knn.kneighbors(ratings_csr[idx], n_neighbors=11)
	knn_recommended_set.update(indices_knn.flatten()[1:]) # skip self at index 0
	# --- SVD Coverage ---
	svd_scores = svd_sim_matrix[idx]
	top_svd = np.argsort(svd_scores)[::-1][1:11] # grab positions 1 through 10
	svd_recommended_set.update(top_svd)
	# --- NMF Coverage ---
	nmf_scores = nmf_sim_matrix[idx]
	top_nmf = np.argsort(nmf_scores)[::-1][1:11] # grab positions 1 through 10
	nmf_recommended_set.update(top_nmf)

# Convert sets to catalog coverage percentages
knn_coverage = (len(knn_recommended_set) / total_unique_movies) * 100
svd_coverage = (len(svd_recommended_set) / total_unique_movies) * 100
nmf_coverage = (len(nmf_recommended_set) / total_unique_movies) * 100

print("\n--- ITEM CATALOG COVERAGE CALCULATED ---")
print(f"KNN Catalog Coverage: {knn_coverage:.2f}%")
print(f"TruncatedSVD Catalog Coverage: {svd_coverage:.2f}%")
print(f"NMF Catalog Coverage: {nmf_coverage:.2f}%")


Calculating coverage for 200 sample movies...

--- ITEM CATALOG COVERAGE CALCULATED ---
KNN Catalog Coverage: 11.14%
TruncatedSVD Catalog Coverage: 11.43%
NMF Catalog Coverage: 11.30%


In [26]:
# Assemble your tournament metrics into a clean dictionary configuration
leaderboard_data = {
'Model/Algorithm': [
'K-Nearest Neighbors (KNN)',
'Truncated SVD',
'Non-Negative Matrix Factorization (NMF)',
'K-Means Clustering'
],
'Model Architecture': [
'Instance-Based (Similarity)',
'Matrix Factorization',
'Matrix Factorization',
'Clustering (Unsupervised)'
],
'Reconstruction Error (MSE)': [
'N/A',
f"{svd_mse:.6f}",
f"{nmf_mse:.6f}",
'N/A'
],
'Catalog Coverage (%)': [
f"{knn_coverage:.2f}%",
f"{svd_coverage:.2f}%",
f"{nmf_coverage:.2f}%",
'N/A (Group Assignment Only)'
],
'Inference Computation': [
'Heavy (On-the-fly distance calc)',
'Instant (Matrix dot product lookup)',
'Instant (Matrix dot product lookup)',
'Instant (Cluster query)'
]
}

# Convert the dictionary layout into a Pandas DataFrame
leaderboard_df = pd.DataFrame(leaderboard_data)

# Set Model/Algorithm as index for clean table formatting
leaderboard_df.set_index('Model/Algorithm', inplace=True)

# Display the final summary leaderboard console output
leaderboard_df 


,Model Architecture,Reconstruction Error (MSE),Catalog Coverage (%),Inference Computation
Model/Algorithm,,,,
K-Nearest Neighbors (KNN),Instance-Based (Similarity),N/A,11.14%,Heavy (On-the-fly distance calc)
Truncated SVD,Matrix Factorization,0.108398,11.43%,Instant (Matrix dot product lookup)
Non-Negative Matrix Factorization (NMF),Matrix Factorization,0.113584,11.30%,Instant (Matrix dot product lookup)
K-Means Clustering,Clustering (Unsupervised),N/A,N/A (Group Assignment Only),Instant (Cluster query)
